master:
   build: .

   volumes:
    - ./code:/code 
    - ./initdb:/docker-entrypoint-initdb.d 
  
   environment:
    - BOOTSTRAP=true

   expose:
    - "3306"
    - "4567"
    - "4568"
    - "4444"
  
   ports:
    - "3306:3306"
   
   volumes:
    - cluster_conf:/cluster.conf.d
  
node:
   build: .

   ports:
    - "3306"    

   links:
    - master
   
   volumes_from:
    - master

